### Stage 1: build ###

FROM node:14.18.0 as build

# Set working directory.
RUN mkdir /app
WORKDIR /app

# Copy app dependencies.
COPY . /app/

# Install app dependencies.
RUN npm install

# Build app
#RUN npm run build

# CMD npm start -- --prod --host 0.0.0.0 --port 4300

RUN npm run build -- --prod

# USER node

FROM nginx:1.21.3-alpine

COPY --from=build /app/dist /usr/share/nginx/html/navigator

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d/navigator-ui.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 4300
