### Stage 1: build ###

FROM node:14.18.0

# Set working directory.
RUN mkdir /app
WORKDIR /app

# Copy app dependencies.
COPY . /app/

# Install app dependencies.
RUN npm install

# Build app
#RUN npm run build

#CMD npm  start -- --host 0.0.0.0 --port 4300
