# pull the base image
FROM node:16.13.2-alpine

# set the working direction
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./

COPY package-lock.json ./

#COPY node_modules /app/

RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
# add app
# COPY . ./

USER node

# start app
CMD ["npm", "start"]
