export const ATTACK_EMULATION = "Attack Emulation";
export const USERS = "Users";
export const AUDIT_LOGS = "Audit Logs";
export const ACDS_NAVIGATOR = "ACDS-Navigator";
export const UPDATE_ATTACK = "updateAttack";
export const UPDATE_TECHNIQUE = "updateTechnique";
export const UPDATE_MACHINE = "updateMachine";
export const INTEGRATIONS = "Integrations";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

//authentication
export const AUTH = {
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const COMMON_ACTION = {
  PAGE_LOADING: "PAGE_LOADING",
  PAGE_LOADED: "PAGE_LOADED",
};

export const POLICY_MANAGER = {
  FETCH_POLICY_SUCCESS: "FETCH_POLICY_SUCCESS",
  FETCH_POLICY_FAIL: "FETCH_POLICY_FAIL",
  FETCH_POLICY_SERVER_ERROR: "FETCH_POLICY_SERVER_ERROR",
  STORE_POLICY_SUCCESS: "STORE_POLICY_SUCCESS",
  STORE_POLICY_FAIL: "STORE_POLICY_FAIL",
  STORE_POLICY_SERVER_ERROR: "STORE_POLICY_SERVER_ERROR",
  RESET_DIALOG_MESSAGE: "RESET_DIALOG_MESSAGE"
};
