version: "3.1"

services:

  db:
    container_name: scc-db
    image: docker.acds.net.in/scc/scc_db:${ACDS_SCC_VERSION}
    restart: always
    networks:
      - scc_backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=scc_db
      - PGDATA=/var/lib/postgresql/data/pgdata
#    ports:
#      - 5432:5432
#    env_file:
#      - ./db/db.env
    volumes:
      - ./scc-db/scc.sql:/docker-entrypoint-initdb.d/init.sql
      - sccdata:/var/lib/postgresql/data

  adminer:
    container_name: scc-adminer
    image: docker.acds.net.in/scc/scc_adminer:${ACDS_SCC_VERSION}
    restart: always
    networks:
      - scc_backend
    ports:
      - 8080:8080

  app1:
    container_name: scc-java
    image: docker.acds.net.in/scc/scc_app1:${ACDS_SCC_VERSION}
    restart: always
    ports:
      - "8443:8443"
    networks: 
      - scc_backend
      - scc_frontend

  web:
    container_name: scc-ui
    image: docker.acds.net.in/scc/scc_web:${ACDS_SCC_VERSION}
    restart: always
    env_file: 
      - ./.env.prod
    volumes:
      - ./ssl:/etc/nginx/ssl/
    ports:
      - "443:443"
    networks: 
      - scc_frontend

networks:
  scc_backend:
      driver: bridge
  scc_frontend:
      driver: bridge

volumes:
  sccdata:
