# Build stage

FROM node:14.18.0 as build

RUN mkdir /app
WORKDIR /app

# copy over needed files
COPY . ./

RUN chown -R node:node ./

RUN npm install --unsafe-perm

# EXPOSE 4200

# CMD ["npm", "start", "--prod"]

# USER node

RUN npm run build -- --prod --aot=false --build-optimizer=false

USER node

FROM nginx:1.21.3-alpine

COPY --from=build /app/dist /usr/share/nginx/html/

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d/matrix-ui.conf

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 4200