# Build stage

FROM node:14.18.0

RUN mkdir /app
WORKDIR /app

# copy over needed files
COPY . ./

# give user permissions
RUN chown -R node:node ./

RUN npm install --unsafe-perm

#EXPOSE 4200

# CMD ["npm", "start"]

# USER node
